//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18051
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFan.MyMusicCenterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Proxy/", ConfigurationName="MyMusicCenterService.MyMusicCenterWS")]
    public interface MyMusicCenterWS {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Proxy/MyMusicCenterWS/getArtistsByNameRequest", ReplyAction="http://Proxy/MyMusicCenterWS/getArtistsByNameResponse")]
        MyFan.MyMusicCenterService.getArtistsByNameResponse getArtistsByName(MyFan.MyMusicCenterService.getArtistsByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Proxy/MyMusicCenterWS/getArtistsByNameRequest", ReplyAction="http://Proxy/MyMusicCenterWS/getArtistsByNameResponse")]
        System.Threading.Tasks.Task<MyFan.MyMusicCenterService.getArtistsByNameResponse> getArtistsByNameAsync(MyFan.MyMusicCenterService.getArtistsByNameRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Proxy/MyMusicCenterWS/helloRequest", ReplyAction="http://Proxy/MyMusicCenterWS/helloResponse")]
        MyFan.MyMusicCenterService.helloResponse hello(MyFan.MyMusicCenterService.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Proxy/MyMusicCenterWS/helloRequest", ReplyAction="http://Proxy/MyMusicCenterWS/helloResponse")]
        System.Threading.Tasks.Task<MyFan.MyMusicCenterService.helloResponse> helloAsync(MyFan.MyMusicCenterService.helloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://Proxy/).
        [System.ServiceModel.OperationContractAttribute(Action="http://Proxy/MyMusicCenterWS/updateFollowersRequest", ReplyAction="http://Proxy/MyMusicCenterWS/updateFollowersResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MyFan.MyMusicCenterService.updateFollowersResponse updateFollowers(MyFan.MyMusicCenterService.updateFollowersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Proxy/MyMusicCenterWS/updateFollowersRequest", ReplyAction="http://Proxy/MyMusicCenterWS/updateFollowersResponse")]
        System.Threading.Tasks.Task<MyFan.MyMusicCenterService.updateFollowersResponse> updateFollowersAsync(MyFan.MyMusicCenterService.updateFollowersRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Proxy/MyMusicCenterWS/getArtistByIdRequest", ReplyAction="http://Proxy/MyMusicCenterWS/getArtistByIdResponse")]
        MyFan.MyMusicCenterService.getArtistByIdResponse getArtistById(MyFan.MyMusicCenterService.getArtistByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Proxy/MyMusicCenterWS/getArtistByIdRequest", ReplyAction="http://Proxy/MyMusicCenterWS/getArtistByIdResponse")]
        System.Threading.Tasks.Task<MyFan.MyMusicCenterService.getArtistByIdResponse> getArtistByIdAsync(MyFan.MyMusicCenterService.getArtistByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getArtistsByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getArtistsByName", Namespace="http://Proxy/", Order=0)]
        public MyFan.MyMusicCenterService.getArtistsByNameRequestBody Body;
        
        public getArtistsByNameRequest() {
        }
        
        public getArtistsByNameRequest(MyFan.MyMusicCenterService.getArtistsByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getArtistsByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public getArtistsByNameRequestBody() {
        }
        
        public getArtistsByNameRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getArtistsByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getArtistsByNameResponse", Namespace="http://Proxy/", Order=0)]
        public MyFan.MyMusicCenterService.getArtistsByNameResponseBody Body;
        
        public getArtistsByNameResponse() {
        }
        
        public getArtistsByNameResponse(MyFan.MyMusicCenterService.getArtistsByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getArtistsByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getArtistsByNameResponseBody() {
        }
        
        public getArtistsByNameResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://Proxy/", Order=0)]
        public MyFan.MyMusicCenterService.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(MyFan.MyMusicCenterService.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://Proxy/", Order=0)]
        public MyFan.MyMusicCenterService.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(MyFan.MyMusicCenterService.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateFollowers", WrapperNamespace="http://Proxy/", IsWrapped=true)]
    public partial class updateFollowersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int follow;
        
        public updateFollowersRequest() {
        }
        
        public updateFollowersRequest(int id, int follow) {
            this.id = id;
            this.follow = follow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateFollowersResponse", WrapperNamespace="http://Proxy/", IsWrapped=true)]
    public partial class updateFollowersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public updateFollowersResponse() {
        }
        
        public updateFollowersResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getArtistByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getArtistById", Namespace="http://Proxy/", Order=0)]
        public MyFan.MyMusicCenterService.getArtistByIdRequestBody Body;
        
        public getArtistByIdRequest() {
        }
        
        public getArtistByIdRequest(MyFan.MyMusicCenterService.getArtistByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getArtistByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getArtistByIdRequestBody() {
        }
        
        public getArtistByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getArtistByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getArtistByIdResponse", Namespace="http://Proxy/", Order=0)]
        public MyFan.MyMusicCenterService.getArtistByIdResponseBody Body;
        
        public getArtistByIdResponse() {
        }
        
        public getArtistByIdResponse(MyFan.MyMusicCenterService.getArtistByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getArtistByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getArtistByIdResponseBody() {
        }
        
        public getArtistByIdResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyMusicCenterWSChannel : MyFan.MyMusicCenterService.MyMusicCenterWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyMusicCenterWSClient : System.ServiceModel.ClientBase<MyFan.MyMusicCenterService.MyMusicCenterWS>, MyFan.MyMusicCenterService.MyMusicCenterWS {
        
        public MyMusicCenterWSClient() {
        }
        
        public MyMusicCenterWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyMusicCenterWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyMusicCenterWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyMusicCenterWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyFan.MyMusicCenterService.getArtistsByNameResponse MyFan.MyMusicCenterService.MyMusicCenterWS.getArtistsByName(MyFan.MyMusicCenterService.getArtistsByNameRequest request) {
            return base.Channel.getArtistsByName(request);
        }
        
        public string getArtistsByName(string name) {
            MyFan.MyMusicCenterService.getArtistsByNameRequest inValue = new MyFan.MyMusicCenterService.getArtistsByNameRequest();
            inValue.Body = new MyFan.MyMusicCenterService.getArtistsByNameRequestBody();
            inValue.Body.name = name;
            MyFan.MyMusicCenterService.getArtistsByNameResponse retVal = ((MyFan.MyMusicCenterService.MyMusicCenterWS)(this)).getArtistsByName(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyFan.MyMusicCenterService.getArtistsByNameResponse> MyFan.MyMusicCenterService.MyMusicCenterWS.getArtistsByNameAsync(MyFan.MyMusicCenterService.getArtistsByNameRequest request) {
            return base.Channel.getArtistsByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyFan.MyMusicCenterService.getArtistsByNameResponse> getArtistsByNameAsync(string name) {
            MyFan.MyMusicCenterService.getArtistsByNameRequest inValue = new MyFan.MyMusicCenterService.getArtistsByNameRequest();
            inValue.Body = new MyFan.MyMusicCenterService.getArtistsByNameRequestBody();
            inValue.Body.name = name;
            return ((MyFan.MyMusicCenterService.MyMusicCenterWS)(this)).getArtistsByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyFan.MyMusicCenterService.helloResponse MyFan.MyMusicCenterService.MyMusicCenterWS.hello(MyFan.MyMusicCenterService.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            MyFan.MyMusicCenterService.helloRequest inValue = new MyFan.MyMusicCenterService.helloRequest();
            inValue.Body = new MyFan.MyMusicCenterService.helloRequestBody();
            inValue.Body.name = name;
            MyFan.MyMusicCenterService.helloResponse retVal = ((MyFan.MyMusicCenterService.MyMusicCenterWS)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyFan.MyMusicCenterService.helloResponse> MyFan.MyMusicCenterService.MyMusicCenterWS.helloAsync(MyFan.MyMusicCenterService.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyFan.MyMusicCenterService.helloResponse> helloAsync(string name) {
            MyFan.MyMusicCenterService.helloRequest inValue = new MyFan.MyMusicCenterService.helloRequest();
            inValue.Body = new MyFan.MyMusicCenterService.helloRequestBody();
            inValue.Body.name = name;
            return ((MyFan.MyMusicCenterService.MyMusicCenterWS)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyFan.MyMusicCenterService.updateFollowersResponse MyFan.MyMusicCenterService.MyMusicCenterWS.updateFollowers(MyFan.MyMusicCenterService.updateFollowersRequest request) {
            return base.Channel.updateFollowers(request);
        }
        
        public int updateFollowers(int id, int follow) {
            MyFan.MyMusicCenterService.updateFollowersRequest inValue = new MyFan.MyMusicCenterService.updateFollowersRequest();
            inValue.id = id;
            inValue.follow = follow;
            MyFan.MyMusicCenterService.updateFollowersResponse retVal = ((MyFan.MyMusicCenterService.MyMusicCenterWS)(this)).updateFollowers(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyFan.MyMusicCenterService.updateFollowersResponse> MyFan.MyMusicCenterService.MyMusicCenterWS.updateFollowersAsync(MyFan.MyMusicCenterService.updateFollowersRequest request) {
            return base.Channel.updateFollowersAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyFan.MyMusicCenterService.updateFollowersResponse> updateFollowersAsync(int id, int follow) {
            MyFan.MyMusicCenterService.updateFollowersRequest inValue = new MyFan.MyMusicCenterService.updateFollowersRequest();
            inValue.id = id;
            inValue.follow = follow;
            return ((MyFan.MyMusicCenterService.MyMusicCenterWS)(this)).updateFollowersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyFan.MyMusicCenterService.getArtistByIdResponse MyFan.MyMusicCenterService.MyMusicCenterWS.getArtistById(MyFan.MyMusicCenterService.getArtistByIdRequest request) {
            return base.Channel.getArtistById(request);
        }
        
        public string getArtistById(int id) {
            MyFan.MyMusicCenterService.getArtistByIdRequest inValue = new MyFan.MyMusicCenterService.getArtistByIdRequest();
            inValue.Body = new MyFan.MyMusicCenterService.getArtistByIdRequestBody();
            inValue.Body.id = id;
            MyFan.MyMusicCenterService.getArtistByIdResponse retVal = ((MyFan.MyMusicCenterService.MyMusicCenterWS)(this)).getArtistById(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyFan.MyMusicCenterService.getArtistByIdResponse> MyFan.MyMusicCenterService.MyMusicCenterWS.getArtistByIdAsync(MyFan.MyMusicCenterService.getArtistByIdRequest request) {
            return base.Channel.getArtistByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyFan.MyMusicCenterService.getArtistByIdResponse> getArtistByIdAsync(int id) {
            MyFan.MyMusicCenterService.getArtistByIdRequest inValue = new MyFan.MyMusicCenterService.getArtistByIdRequest();
            inValue.Body = new MyFan.MyMusicCenterService.getArtistByIdRequestBody();
            inValue.Body.id = id;
            return ((MyFan.MyMusicCenterService.MyMusicCenterWS)(this)).getArtistByIdAsync(inValue);
        }
    }
}
