//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18051
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFan.MyMusicCenterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Proxy/", ConfigurationName="MyMusicCenterService.MyMusicCenterWS")]
    public interface MyMusicCenterWS {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Proxy/MyMusicCenterWS/getDiscByIdRequest", ReplyAction="http://Proxy/MyMusicCenterWS/getDiscByIdResponse")]
        MyFan.MyMusicCenterService.getDiscByIdResponse getDiscById(MyFan.MyMusicCenterService.getDiscByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Proxy/MyMusicCenterWS/getDiscByIdRequest", ReplyAction="http://Proxy/MyMusicCenterWS/getDiscByIdResponse")]
        System.Threading.Tasks.Task<MyFan.MyMusicCenterService.getDiscByIdResponse> getDiscByIdAsync(MyFan.MyMusicCenterService.getDiscByIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Proxy/MyMusicCenterWS/getArtistByIdRequest", ReplyAction="http://Proxy/MyMusicCenterWS/getArtistByIdResponse")]
        MyFan.MyMusicCenterService.getArtistByIdResponse getArtistById(MyFan.MyMusicCenterService.getArtistByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Proxy/MyMusicCenterWS/getArtistByIdRequest", ReplyAction="http://Proxy/MyMusicCenterWS/getArtistByIdResponse")]
        System.Threading.Tasks.Task<MyFan.MyMusicCenterService.getArtistByIdResponse> getArtistByIdAsync(MyFan.MyMusicCenterService.getArtistByIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Proxy/MyMusicCenterWS/getArtistsByNameRequest", ReplyAction="http://Proxy/MyMusicCenterWS/getArtistsByNameResponse")]
        MyFan.MyMusicCenterService.getArtistsByNameResponse getArtistsByName(MyFan.MyMusicCenterService.getArtistsByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Proxy/MyMusicCenterWS/getArtistsByNameRequest", ReplyAction="http://Proxy/MyMusicCenterWS/getArtistsByNameResponse")]
        System.Threading.Tasks.Task<MyFan.MyMusicCenterService.getArtistsByNameResponse> getArtistsByNameAsync(MyFan.MyMusicCenterService.getArtistsByNameRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://Proxy/).
        [System.ServiceModel.OperationContractAttribute(Action="http://Proxy/MyMusicCenterWS/updateFollowersRequest", ReplyAction="http://Proxy/MyMusicCenterWS/updateFollowersResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MyFan.MyMusicCenterService.updateFollowersResponse updateFollowers(MyFan.MyMusicCenterService.updateFollowersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Proxy/MyMusicCenterWS/updateFollowersRequest", ReplyAction="http://Proxy/MyMusicCenterWS/updateFollowersResponse")]
        System.Threading.Tasks.Task<MyFan.MyMusicCenterService.updateFollowersResponse> updateFollowersAsync(MyFan.MyMusicCenterService.updateFollowersRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Proxy/MyMusicCenterWS/getNewsByArtistIdRequest", ReplyAction="http://Proxy/MyMusicCenterWS/getNewsByArtistIdResponse")]
        MyFan.MyMusicCenterService.getNewsByArtistIdResponse getNewsByArtistId(MyFan.MyMusicCenterService.getNewsByArtistIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Proxy/MyMusicCenterWS/getNewsByArtistIdRequest", ReplyAction="http://Proxy/MyMusicCenterWS/getNewsByArtistIdResponse")]
        System.Threading.Tasks.Task<MyFan.MyMusicCenterService.getNewsByArtistIdResponse> getNewsByArtistIdAsync(MyFan.MyMusicCenterService.getNewsByArtistIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Proxy/MyMusicCenterWS/getDiscsByArtistIdRequest", ReplyAction="http://Proxy/MyMusicCenterWS/getDiscsByArtistIdResponse")]
        MyFan.MyMusicCenterService.getDiscsByArtistIdResponse getDiscsByArtistId(MyFan.MyMusicCenterService.getDiscsByArtistIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Proxy/MyMusicCenterWS/getDiscsByArtistIdRequest", ReplyAction="http://Proxy/MyMusicCenterWS/getDiscsByArtistIdResponse")]
        System.Threading.Tasks.Task<MyFan.MyMusicCenterService.getDiscsByArtistIdResponse> getDiscsByArtistIdAsync(MyFan.MyMusicCenterService.getDiscsByArtistIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Proxy/MyMusicCenterWS/helloRequest", ReplyAction="http://Proxy/MyMusicCenterWS/helloResponse")]
        MyFan.MyMusicCenterService.helloResponse hello(MyFan.MyMusicCenterService.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Proxy/MyMusicCenterWS/helloRequest", ReplyAction="http://Proxy/MyMusicCenterWS/helloResponse")]
        System.Threading.Tasks.Task<MyFan.MyMusicCenterService.helloResponse> helloAsync(MyFan.MyMusicCenterService.helloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Proxy/MyMusicCenterWS/getNewsByIdRequest", ReplyAction="http://Proxy/MyMusicCenterWS/getNewsByIdResponse")]
        MyFan.MyMusicCenterService.getNewsByIdResponse getNewsById(MyFan.MyMusicCenterService.getNewsByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Proxy/MyMusicCenterWS/getNewsByIdRequest", ReplyAction="http://Proxy/MyMusicCenterWS/getNewsByIdResponse")]
        System.Threading.Tasks.Task<MyFan.MyMusicCenterService.getNewsByIdResponse> getNewsByIdAsync(MyFan.MyMusicCenterService.getNewsByIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://Proxy/).
        [System.ServiceModel.OperationContractAttribute(Action="http://Proxy/MyMusicCenterWS/UpdateDiscRatingRequest", ReplyAction="http://Proxy/MyMusicCenterWS/UpdateDiscRatingResponse")]
        MyFan.MyMusicCenterService.UpdateDiscRatingResponse UpdateDiscRating(MyFan.MyMusicCenterService.UpdateDiscRatingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Proxy/MyMusicCenterWS/UpdateDiscRatingRequest", ReplyAction="http://Proxy/MyMusicCenterWS/UpdateDiscRatingResponse")]
        System.Threading.Tasks.Task<MyFan.MyMusicCenterService.UpdateDiscRatingResponse> UpdateDiscRatingAsync(MyFan.MyMusicCenterService.UpdateDiscRatingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDiscByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDiscById", Namespace="http://Proxy/", Order=0)]
        public MyFan.MyMusicCenterService.getDiscByIdRequestBody Body;
        
        public getDiscByIdRequest() {
        }
        
        public getDiscByIdRequest(MyFan.MyMusicCenterService.getDiscByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getDiscByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getDiscByIdRequestBody() {
        }
        
        public getDiscByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDiscByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDiscByIdResponse", Namespace="http://Proxy/", Order=0)]
        public MyFan.MyMusicCenterService.getDiscByIdResponseBody Body;
        
        public getDiscByIdResponse() {
        }
        
        public getDiscByIdResponse(MyFan.MyMusicCenterService.getDiscByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getDiscByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getDiscByIdResponseBody() {
        }
        
        public getDiscByIdResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getArtistByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getArtistById", Namespace="http://Proxy/", Order=0)]
        public MyFan.MyMusicCenterService.getArtistByIdRequestBody Body;
        
        public getArtistByIdRequest() {
        }
        
        public getArtistByIdRequest(MyFan.MyMusicCenterService.getArtistByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getArtistByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getArtistByIdRequestBody() {
        }
        
        public getArtistByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getArtistByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getArtistByIdResponse", Namespace="http://Proxy/", Order=0)]
        public MyFan.MyMusicCenterService.getArtistByIdResponseBody Body;
        
        public getArtistByIdResponse() {
        }
        
        public getArtistByIdResponse(MyFan.MyMusicCenterService.getArtistByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getArtistByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getArtistByIdResponseBody() {
        }
        
        public getArtistByIdResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getArtistsByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getArtistsByName", Namespace="http://Proxy/", Order=0)]
        public MyFan.MyMusicCenterService.getArtistsByNameRequestBody Body;
        
        public getArtistsByNameRequest() {
        }
        
        public getArtistsByNameRequest(MyFan.MyMusicCenterService.getArtistsByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getArtistsByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public getArtistsByNameRequestBody() {
        }
        
        public getArtistsByNameRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getArtistsByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getArtistsByNameResponse", Namespace="http://Proxy/", Order=0)]
        public MyFan.MyMusicCenterService.getArtistsByNameResponseBody Body;
        
        public getArtistsByNameResponse() {
        }
        
        public getArtistsByNameResponse(MyFan.MyMusicCenterService.getArtistsByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getArtistsByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getArtistsByNameResponseBody() {
        }
        
        public getArtistsByNameResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateFollowers", WrapperNamespace="http://Proxy/", IsWrapped=true)]
    public partial class updateFollowersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int follow;
        
        public updateFollowersRequest() {
        }
        
        public updateFollowersRequest(int id, int follow) {
            this.id = id;
            this.follow = follow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateFollowersResponse", WrapperNamespace="http://Proxy/", IsWrapped=true)]
    public partial class updateFollowersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public updateFollowersResponse() {
        }
        
        public updateFollowersResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNewsByArtistIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNewsByArtistId", Namespace="http://Proxy/", Order=0)]
        public MyFan.MyMusicCenterService.getNewsByArtistIdRequestBody Body;
        
        public getNewsByArtistIdRequest() {
        }
        
        public getNewsByArtistIdRequest(MyFan.MyMusicCenterService.getNewsByArtistIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getNewsByArtistIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getNewsByArtistIdRequestBody() {
        }
        
        public getNewsByArtistIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNewsByArtistIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNewsByArtistIdResponse", Namespace="http://Proxy/", Order=0)]
        public MyFan.MyMusicCenterService.getNewsByArtistIdResponseBody Body;
        
        public getNewsByArtistIdResponse() {
        }
        
        public getNewsByArtistIdResponse(MyFan.MyMusicCenterService.getNewsByArtistIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getNewsByArtistIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getNewsByArtistIdResponseBody() {
        }
        
        public getNewsByArtistIdResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDiscsByArtistIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDiscsByArtistId", Namespace="http://Proxy/", Order=0)]
        public MyFan.MyMusicCenterService.getDiscsByArtistIdRequestBody Body;
        
        public getDiscsByArtistIdRequest() {
        }
        
        public getDiscsByArtistIdRequest(MyFan.MyMusicCenterService.getDiscsByArtistIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getDiscsByArtistIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getDiscsByArtistIdRequestBody() {
        }
        
        public getDiscsByArtistIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDiscsByArtistIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDiscsByArtistIdResponse", Namespace="http://Proxy/", Order=0)]
        public MyFan.MyMusicCenterService.getDiscsByArtistIdResponseBody Body;
        
        public getDiscsByArtistIdResponse() {
        }
        
        public getDiscsByArtistIdResponse(MyFan.MyMusicCenterService.getDiscsByArtistIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getDiscsByArtistIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getDiscsByArtistIdResponseBody() {
        }
        
        public getDiscsByArtistIdResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://Proxy/", Order=0)]
        public MyFan.MyMusicCenterService.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(MyFan.MyMusicCenterService.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://Proxy/", Order=0)]
        public MyFan.MyMusicCenterService.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(MyFan.MyMusicCenterService.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNewsByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNewsById", Namespace="http://Proxy/", Order=0)]
        public MyFan.MyMusicCenterService.getNewsByIdRequestBody Body;
        
        public getNewsByIdRequest() {
        }
        
        public getNewsByIdRequest(MyFan.MyMusicCenterService.getNewsByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getNewsByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getNewsByIdRequestBody() {
        }
        
        public getNewsByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNewsByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNewsByIdResponse", Namespace="http://Proxy/", Order=0)]
        public MyFan.MyMusicCenterService.getNewsByIdResponseBody Body;
        
        public getNewsByIdResponse() {
        }
        
        public getNewsByIdResponse(MyFan.MyMusicCenterService.getNewsByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getNewsByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getNewsByIdResponseBody() {
        }
        
        public getNewsByIdResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDiscRating", WrapperNamespace="http://Proxy/", IsWrapped=true)]
    public partial class UpdateDiscRatingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double rating;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int comments;
        
        public UpdateDiscRatingRequest() {
        }
        
        public UpdateDiscRatingRequest(double rating, int comments) {
            this.rating = rating;
            this.comments = comments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDiscRatingResponse", WrapperNamespace="http://Proxy/", IsWrapped=true)]
    public partial class UpdateDiscRatingResponse {
        
        public UpdateDiscRatingResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyMusicCenterWSChannel : MyFan.MyMusicCenterService.MyMusicCenterWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyMusicCenterWSClient : System.ServiceModel.ClientBase<MyFan.MyMusicCenterService.MyMusicCenterWS>, MyFan.MyMusicCenterService.MyMusicCenterWS {
        
        public MyMusicCenterWSClient() {
        }
        
        public MyMusicCenterWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyMusicCenterWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyMusicCenterWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyMusicCenterWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyFan.MyMusicCenterService.getDiscByIdResponse MyFan.MyMusicCenterService.MyMusicCenterWS.getDiscById(MyFan.MyMusicCenterService.getDiscByIdRequest request) {
            return base.Channel.getDiscById(request);
        }
        
        public string getDiscById(int id) {
            MyFan.MyMusicCenterService.getDiscByIdRequest inValue = new MyFan.MyMusicCenterService.getDiscByIdRequest();
            inValue.Body = new MyFan.MyMusicCenterService.getDiscByIdRequestBody();
            inValue.Body.id = id;
            MyFan.MyMusicCenterService.getDiscByIdResponse retVal = ((MyFan.MyMusicCenterService.MyMusicCenterWS)(this)).getDiscById(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyFan.MyMusicCenterService.getDiscByIdResponse> MyFan.MyMusicCenterService.MyMusicCenterWS.getDiscByIdAsync(MyFan.MyMusicCenterService.getDiscByIdRequest request) {
            return base.Channel.getDiscByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyFan.MyMusicCenterService.getDiscByIdResponse> getDiscByIdAsync(int id) {
            MyFan.MyMusicCenterService.getDiscByIdRequest inValue = new MyFan.MyMusicCenterService.getDiscByIdRequest();
            inValue.Body = new MyFan.MyMusicCenterService.getDiscByIdRequestBody();
            inValue.Body.id = id;
            return ((MyFan.MyMusicCenterService.MyMusicCenterWS)(this)).getDiscByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyFan.MyMusicCenterService.getArtistByIdResponse MyFan.MyMusicCenterService.MyMusicCenterWS.getArtistById(MyFan.MyMusicCenterService.getArtistByIdRequest request) {
            return base.Channel.getArtistById(request);
        }
        
        public string getArtistById(int id) {
            MyFan.MyMusicCenterService.getArtistByIdRequest inValue = new MyFan.MyMusicCenterService.getArtistByIdRequest();
            inValue.Body = new MyFan.MyMusicCenterService.getArtistByIdRequestBody();
            inValue.Body.id = id;
            MyFan.MyMusicCenterService.getArtistByIdResponse retVal = ((MyFan.MyMusicCenterService.MyMusicCenterWS)(this)).getArtistById(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyFan.MyMusicCenterService.getArtistByIdResponse> MyFan.MyMusicCenterService.MyMusicCenterWS.getArtistByIdAsync(MyFan.MyMusicCenterService.getArtistByIdRequest request) {
            return base.Channel.getArtistByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyFan.MyMusicCenterService.getArtistByIdResponse> getArtistByIdAsync(int id) {
            MyFan.MyMusicCenterService.getArtistByIdRequest inValue = new MyFan.MyMusicCenterService.getArtistByIdRequest();
            inValue.Body = new MyFan.MyMusicCenterService.getArtistByIdRequestBody();
            inValue.Body.id = id;
            return ((MyFan.MyMusicCenterService.MyMusicCenterWS)(this)).getArtistByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyFan.MyMusicCenterService.getArtistsByNameResponse MyFan.MyMusicCenterService.MyMusicCenterWS.getArtistsByName(MyFan.MyMusicCenterService.getArtistsByNameRequest request) {
            return base.Channel.getArtistsByName(request);
        }
        
        public string getArtistsByName(string name) {
            MyFan.MyMusicCenterService.getArtistsByNameRequest inValue = new MyFan.MyMusicCenterService.getArtistsByNameRequest();
            inValue.Body = new MyFan.MyMusicCenterService.getArtistsByNameRequestBody();
            inValue.Body.name = name;
            MyFan.MyMusicCenterService.getArtistsByNameResponse retVal = ((MyFan.MyMusicCenterService.MyMusicCenterWS)(this)).getArtistsByName(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyFan.MyMusicCenterService.getArtistsByNameResponse> MyFan.MyMusicCenterService.MyMusicCenterWS.getArtistsByNameAsync(MyFan.MyMusicCenterService.getArtistsByNameRequest request) {
            return base.Channel.getArtistsByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyFan.MyMusicCenterService.getArtistsByNameResponse> getArtistsByNameAsync(string name) {
            MyFan.MyMusicCenterService.getArtistsByNameRequest inValue = new MyFan.MyMusicCenterService.getArtistsByNameRequest();
            inValue.Body = new MyFan.MyMusicCenterService.getArtistsByNameRequestBody();
            inValue.Body.name = name;
            return ((MyFan.MyMusicCenterService.MyMusicCenterWS)(this)).getArtistsByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyFan.MyMusicCenterService.updateFollowersResponse MyFan.MyMusicCenterService.MyMusicCenterWS.updateFollowers(MyFan.MyMusicCenterService.updateFollowersRequest request) {
            return base.Channel.updateFollowers(request);
        }
        
        public int updateFollowers(int id, int follow) {
            MyFan.MyMusicCenterService.updateFollowersRequest inValue = new MyFan.MyMusicCenterService.updateFollowersRequest();
            inValue.id = id;
            inValue.follow = follow;
            MyFan.MyMusicCenterService.updateFollowersResponse retVal = ((MyFan.MyMusicCenterService.MyMusicCenterWS)(this)).updateFollowers(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyFan.MyMusicCenterService.updateFollowersResponse> MyFan.MyMusicCenterService.MyMusicCenterWS.updateFollowersAsync(MyFan.MyMusicCenterService.updateFollowersRequest request) {
            return base.Channel.updateFollowersAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyFan.MyMusicCenterService.updateFollowersResponse> updateFollowersAsync(int id, int follow) {
            MyFan.MyMusicCenterService.updateFollowersRequest inValue = new MyFan.MyMusicCenterService.updateFollowersRequest();
            inValue.id = id;
            inValue.follow = follow;
            return ((MyFan.MyMusicCenterService.MyMusicCenterWS)(this)).updateFollowersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyFan.MyMusicCenterService.getNewsByArtistIdResponse MyFan.MyMusicCenterService.MyMusicCenterWS.getNewsByArtistId(MyFan.MyMusicCenterService.getNewsByArtistIdRequest request) {
            return base.Channel.getNewsByArtistId(request);
        }
        
        public string getNewsByArtistId(int id) {
            MyFan.MyMusicCenterService.getNewsByArtistIdRequest inValue = new MyFan.MyMusicCenterService.getNewsByArtistIdRequest();
            inValue.Body = new MyFan.MyMusicCenterService.getNewsByArtistIdRequestBody();
            inValue.Body.id = id;
            MyFan.MyMusicCenterService.getNewsByArtistIdResponse retVal = ((MyFan.MyMusicCenterService.MyMusicCenterWS)(this)).getNewsByArtistId(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyFan.MyMusicCenterService.getNewsByArtistIdResponse> MyFan.MyMusicCenterService.MyMusicCenterWS.getNewsByArtistIdAsync(MyFan.MyMusicCenterService.getNewsByArtistIdRequest request) {
            return base.Channel.getNewsByArtistIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyFan.MyMusicCenterService.getNewsByArtistIdResponse> getNewsByArtistIdAsync(int id) {
            MyFan.MyMusicCenterService.getNewsByArtistIdRequest inValue = new MyFan.MyMusicCenterService.getNewsByArtistIdRequest();
            inValue.Body = new MyFan.MyMusicCenterService.getNewsByArtistIdRequestBody();
            inValue.Body.id = id;
            return ((MyFan.MyMusicCenterService.MyMusicCenterWS)(this)).getNewsByArtistIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyFan.MyMusicCenterService.getDiscsByArtistIdResponse MyFan.MyMusicCenterService.MyMusicCenterWS.getDiscsByArtistId(MyFan.MyMusicCenterService.getDiscsByArtistIdRequest request) {
            return base.Channel.getDiscsByArtistId(request);
        }
        
        public string getDiscsByArtistId(int id) {
            MyFan.MyMusicCenterService.getDiscsByArtistIdRequest inValue = new MyFan.MyMusicCenterService.getDiscsByArtistIdRequest();
            inValue.Body = new MyFan.MyMusicCenterService.getDiscsByArtistIdRequestBody();
            inValue.Body.id = id;
            MyFan.MyMusicCenterService.getDiscsByArtistIdResponse retVal = ((MyFan.MyMusicCenterService.MyMusicCenterWS)(this)).getDiscsByArtistId(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyFan.MyMusicCenterService.getDiscsByArtistIdResponse> MyFan.MyMusicCenterService.MyMusicCenterWS.getDiscsByArtistIdAsync(MyFan.MyMusicCenterService.getDiscsByArtistIdRequest request) {
            return base.Channel.getDiscsByArtistIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyFan.MyMusicCenterService.getDiscsByArtistIdResponse> getDiscsByArtistIdAsync(int id) {
            MyFan.MyMusicCenterService.getDiscsByArtistIdRequest inValue = new MyFan.MyMusicCenterService.getDiscsByArtistIdRequest();
            inValue.Body = new MyFan.MyMusicCenterService.getDiscsByArtistIdRequestBody();
            inValue.Body.id = id;
            return ((MyFan.MyMusicCenterService.MyMusicCenterWS)(this)).getDiscsByArtistIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyFan.MyMusicCenterService.helloResponse MyFan.MyMusicCenterService.MyMusicCenterWS.hello(MyFan.MyMusicCenterService.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            MyFan.MyMusicCenterService.helloRequest inValue = new MyFan.MyMusicCenterService.helloRequest();
            inValue.Body = new MyFan.MyMusicCenterService.helloRequestBody();
            inValue.Body.name = name;
            MyFan.MyMusicCenterService.helloResponse retVal = ((MyFan.MyMusicCenterService.MyMusicCenterWS)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyFan.MyMusicCenterService.helloResponse> MyFan.MyMusicCenterService.MyMusicCenterWS.helloAsync(MyFan.MyMusicCenterService.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyFan.MyMusicCenterService.helloResponse> helloAsync(string name) {
            MyFan.MyMusicCenterService.helloRequest inValue = new MyFan.MyMusicCenterService.helloRequest();
            inValue.Body = new MyFan.MyMusicCenterService.helloRequestBody();
            inValue.Body.name = name;
            return ((MyFan.MyMusicCenterService.MyMusicCenterWS)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyFan.MyMusicCenterService.getNewsByIdResponse MyFan.MyMusicCenterService.MyMusicCenterWS.getNewsById(MyFan.MyMusicCenterService.getNewsByIdRequest request) {
            return base.Channel.getNewsById(request);
        }
        
        public string getNewsById(int id) {
            MyFan.MyMusicCenterService.getNewsByIdRequest inValue = new MyFan.MyMusicCenterService.getNewsByIdRequest();
            inValue.Body = new MyFan.MyMusicCenterService.getNewsByIdRequestBody();
            inValue.Body.id = id;
            MyFan.MyMusicCenterService.getNewsByIdResponse retVal = ((MyFan.MyMusicCenterService.MyMusicCenterWS)(this)).getNewsById(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyFan.MyMusicCenterService.getNewsByIdResponse> MyFan.MyMusicCenterService.MyMusicCenterWS.getNewsByIdAsync(MyFan.MyMusicCenterService.getNewsByIdRequest request) {
            return base.Channel.getNewsByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyFan.MyMusicCenterService.getNewsByIdResponse> getNewsByIdAsync(int id) {
            MyFan.MyMusicCenterService.getNewsByIdRequest inValue = new MyFan.MyMusicCenterService.getNewsByIdRequest();
            inValue.Body = new MyFan.MyMusicCenterService.getNewsByIdRequestBody();
            inValue.Body.id = id;
            return ((MyFan.MyMusicCenterService.MyMusicCenterWS)(this)).getNewsByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyFan.MyMusicCenterService.UpdateDiscRatingResponse MyFan.MyMusicCenterService.MyMusicCenterWS.UpdateDiscRating(MyFan.MyMusicCenterService.UpdateDiscRatingRequest request) {
            return base.Channel.UpdateDiscRating(request);
        }
        
        public void UpdateDiscRating(double rating, int comments) {
            MyFan.MyMusicCenterService.UpdateDiscRatingRequest inValue = new MyFan.MyMusicCenterService.UpdateDiscRatingRequest();
            inValue.rating = rating;
            inValue.comments = comments;
            MyFan.MyMusicCenterService.UpdateDiscRatingResponse retVal = ((MyFan.MyMusicCenterService.MyMusicCenterWS)(this)).UpdateDiscRating(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyFan.MyMusicCenterService.UpdateDiscRatingResponse> MyFan.MyMusicCenterService.MyMusicCenterWS.UpdateDiscRatingAsync(MyFan.MyMusicCenterService.UpdateDiscRatingRequest request) {
            return base.Channel.UpdateDiscRatingAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyFan.MyMusicCenterService.UpdateDiscRatingResponse> UpdateDiscRatingAsync(double rating, int comments) {
            MyFan.MyMusicCenterService.UpdateDiscRatingRequest inValue = new MyFan.MyMusicCenterService.UpdateDiscRatingRequest();
            inValue.rating = rating;
            inValue.comments = comments;
            return ((MyFan.MyMusicCenterService.MyMusicCenterWS)(this)).UpdateDiscRatingAsync(inValue);
        }
    }
}
